name: AWS-Resource-Manager CI-CD Pipeline

on:
  push:
    branches:
      - "main"
      - "feature/**"
  pull_request:
    branches:
      - "main"

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Create .env file
        run: | 
          echo ACCESS_SECRET=${{ secrets.ACCESS_SECRET }} >> .env 
          echo ACCESS_KEY=${{ secrets.ACCESS_KEY }} >> .env
          echo REGION=${{ secrets.REGION }} >> .env

      - name: Lint Python scripts with Ruff
        run: |
          python -m ruff check src/ tests/ 

      - name: Test with pytest
        run: |
          pytest -s tests/

      - name: Build the package
        run: python -m build

      - name: Upload distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  publish-to-testpypi:
    runs-on: ubuntu-latest
    needs:
    - CI
    if: startsWith(github.ref, 'refs/heads/feature/') || github.ref == 'refs/heads/main'
    steps:
      - name: Download distribution packages
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_PASSWORD }}
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true

  publish-to-pypi:
    runs-on: ubuntu-latest
    needs:
    - CI
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download distribution packages
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_PASSWORD }}
