name: Publish Package to PyPi Repository

on:
  workflow_call

jobs:
  Publish-Test-PyPi:
    runs-on: ubuntu-latest    
    
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download distribution packages
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_PASSWORD }}
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true

  publish-to-pypi:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download distribution packages
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_PASSWORD }}
