name: Lint Python Scripts and Run Tests

on:
  workflow_call

jobs:
  Lint-Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install Build Dependencies
        run: |
          python -m pip install build setuptools
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install Package Dependencies
        run: |
          pip install .[dev]

      - name: Lint Python scripts with Ruff
        run: |
          python -m ruff check src/ tests/

      - name: Run test with pytest
        run: |
            pytest -v tests/

      - name: Build package
        run: python -m build
        working-directory: .
      
      - name: Verify package
        run: |
          pip install dist/*.whl
          python -c "import aws_resource_manager"